SOUPS_ENABLED: true
SOUP_HEAL_AMOUNT: 6
STR_BONUS: 1.5
REGEN_AMOUNT: 1
FEAST_ITEMS_PER_CHEST: 10

ALCHEMIST_POTION_DUR: 25
ALCHEMIST_MAX_EFFECTS: 2
ASSASSIN_MAX_FALL: 4
ASSASSIN_DMG_TAKEN: 1.25
ASSASSIN_DMG_GIVEN: 1.5
BUTCHER_DROP_AMOUNT: 3
CHAMELEON_STR_DUR: 4
DRYAD_REGEN: 6
HUNTER_WOLF_MEAT: 16
ICARUS_REGEN: 5
ICARUS_BONUS_DMG: 3
JUMPER_WEAK_DUR: 3
JUMPER_STR_DUR: 5
MINER_IRON_ORE_CHANCE: 50
POSEIDON_LS: 50
POSEIDON_REGEN: 4
PUDGE_REGEN: 10
PUDGE_MEAT_FOR_LVL: 4
PUDGE_CAP: 5
PYRO_FIRE_DUR: 3
SAPPER_OH_BOMB_FUSE: 2
SAPPER_POISON_CHANCE: 50
SAPPER_FIRE_CHANCE: 50
SAPPER_MELEE_DMG_NERF: 0.75
SAPPER_DIRTY_BOMB_DMG_NERF: 4
SAPPER_MAGNITUDE_X_DENOM: 3
SAPPER_MAGNITUDE_Y_DENOM: 10
SAPPER_MAGNITUDE_Z_DENOM: 3
SCARECROW_CD: 10
SHADOW_DMG_CAP: 60
SHADOW_LIGHT_DMG: 0.25
SHADOW_DARK_DMG: 0.5
TRAWLER_RAREST: 3
TRAWLER_RARE: 12
TRAWLER_SEMI_RARE: 85
TRAWLER_NORMAL: 600
TRAWLER_FIRE: 50
TRAWLER_POISON: 50
VAMP_FIRE_RES: 30
VAMP_START_LS: 10
VAMP_PLAYER_KILL_LS: 10
VAMP_MOB_KILL_LS: 0.5
VAMP_LS_CAP: 75
VIPER_POISON_CHANCE: 80
VIPER_POISON_DUR: 5