name: CabsHGKits
version: '${project.version}'
main: me.stahrry.CabsHGKits.CabsHGKits
api-version: 1.12.2
authors: [ stahrry ]
description: New Hunger Games abilities for the Bukkit Games Spigot plugin!
website: https://github.com/auscubbage
depend:
  - BukkitGames
  - LibsDisguises
  - ProtocolLib