name: HGAbilities2021
version: '${project.version}'
main: me.stahrry.hgabilities2021.HGAbilities2021
api-version: 1.12.2
authors: [ stahrry ]
description: New Hunger Games abilities for the Bukkit Games Spigot plugin!
website: https://github.com/adcub
depend:
  - BukkitGames
  - LibsDisguises
  - ProtocolLib